---

- name: Redmine
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: devops-example-app
    image: redmine:4.2
    ports:
      - "{{ APP_PORT}}":3000
    env:
      REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
      REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
      REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
      REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
      REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
